on: 
  push:
    branches:
      - dev
name: 🚀 [DEV] Deploy website
jobs:
  web-deploy:
    name: 🎉 Deploy dev
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_LAB }}
        password: ${{ secrets.FTP_PASSWORD_LAB }}
        server-dir: test-github-actions/dev/